Features
Chaw-Ma-Ma-Win/Animation-Studio pull request #1
Opened 2023-08-09 17:34 UTC by Chaw-Ma-Ma-Win

### Features

- Add images with HTML
- Styling with CSS
- Making action with JavaScript

2023-08-09 18:22 UTC, Olamarx requested changes
Hi @Chaw-Ma-Ma-Win, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"/>

## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- Both Home and About pages deployed ✔️

## Required Changes ♻️
_Check the comments under the review._
### Most of your changes are in the main branch, I would have invalidated it but I will encourage you to take note of this.
- [ ] I will encourage you to make a link from the About page to the home page, at the moment, even the logo is not a link to the home page, kindly work on that.
- [ ] I will encourage you to use section to start the mobile menu and avoid the generic semantic tag of div for it to be more semantic.
![image](https://github.com/Chaw-Ma-Ma-Win/Animation-Studio/assets/86200356/6b730161-9457-476f-b42e-fef7100b7059)
- [ ] I can see most of your image tags don't have alt attribute, I will encourage you to add it so that it can be accessed by other devices like screen readers.
- [ ] I can see you did not use the mobile-first styling approach, the mobile-first approach is important because most sites are visited with mobile and it is professionally recommended to do it, I will implore you to adopt it too.
![image](https://github.com/Chaw-Ma-Ma-Win/Animation-Studio/assets/86200356/edc874fe-e13f-4eec-8a28-f6de4e2fde3b)
 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 03:56 UTC, Munsa1 requested changes
Hi @Chaw-Ma-Ma-Win, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-08-10 03:56 UTC, Munsa1 commented on about.html
>          <li><a href="#">Program</a></li>
- [ ] As requested by the previous reviewer, kindly add a link in the `About` page in the navigation to the `Home` page for improved accessibility.

![image](https://github.com/Chaw-Ma-Ma-Win/Animation-Studio/assets/81932478/30a50e31-955b-41cf-91f8-8d800df48ea4)
Change the name of the `About` link to `Home` and change the `href` attribute to point to the index page so that a user can go back to the home page via the link.

2023-08-10 03:56 UTC, Munsa1 commented on index.html
>              </div>
- [ ] (Optional) Kindly consider fixing your design so as to match the given design in terms of layout for a more professional website.
- [ ] Notice you have overflowing content

Your design
![image](https://github.com/Chaw-Ma-Ma-Win/Animation-Studio/assets/81932478/774ae3bf-0199-4dcb-8c35-52af4459ab57)

Given template
![image](https://github.com/Chaw-Ma-Ma-Win/Animation-Studio/assets/81932478/36417f83-bbaa-47f8-8a45-7383babc43e9)

2023-08-10 04:49 UTC, Munsa1 approved these changes
Hi @Chaw-Ma-Ma-Win, 
![congrats](https://github.com/Chaw-Ma-Ma-Win/Animation-Studio/assets/81932478/b2a39565-7d49-44af-bcd9-cb80b21175c1)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-08-10 05:04 UTC, Munsa1 commented
Hey @Chaw-Ma-Ma-Win  some requirements were missed by the previous reviewer, kindly note that the linters were not set up correctly my review may be reverted

2023-08-10 05:19 UTC, Munsa1 commented
Please do not close this pull request as senior reviewers are taking a look at it and will advise on how to proceed

2023-08-10 20:59 UTC, Munsa1 commented
Hey @Chaw-Ma-Ma-Win  I have not received any feedback, I think you can merge. Just a reminder going forward please set up your linters correctly and ensure that all checks pass as per the requirement

2023-08-11 10:11 UTC, bellom commented
@Chaw-Ma-Ma-Win Kindly go ahead and merge.

@Munsa1 - The issue might be from GH, I can see all linters before your review.

Sean
CR Leader.

2023-08-11 11:15 UTC, merged

2023-08-11 11:16 UTC, Chaw-Ma-Ma-Win commented
Done.

၂၀၂၃- ဩ ၁၁- သော PM ၄:၄၁ တွင် Oluwaseun Bello ***@***.***> က
ရေးခဲ့သည်−

> @Chaw-Ma-Ma-Win <https://github.com/Chaw-Ma-Ma-Win> Kindly go ahead and
> merge.
>
> @Munsa1 <https://github.com/Munsa1> - The issue might be from GH, I can
> see all linters before your review.
>
> Sean
> CR Leader.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Chaw-Ma-Ma-Win/Animation-Studio/pull/1#issuecomment-1674514683>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZYZ2YDIHQ6M5ERPM4JBETLXUYANPANCNFSM6AAAAAA3KKXCHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>